#!/bin/bash
set -eu

get_public_ip() {
  # Define a list of HTTP-based providers
  local PROVIDERS=(
    "http://ifconfig.me"
    "http://api.ipify.org"
    "http://ipecho.net/plain"
    "http://v4.ident.me"
  )
  # Iterate through the providers until an IP is found or the list is exhausted
  for provider in "${PROVIDERS[@]}"; do
    local IP
    IP=$(curl -s "$provider")
    # Check if IP contains a valid format (simple regex for an IPv4 address)
    if [[ $IP =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
      echo "$IP"
      return 0
    fi
  done
  return 1
}

if PUBLIC_IP=$(get_public_ip); then
  echo "fetched public IP is: $PUBLIC_IP"
else
  echo "Could not retrieve public IP."
  exit 8
fi
export OP_NODE_P2P_ADVERTISE_IP=$PUBLIC_IP
#export OP_NODE_P2P_BOOTNODES=enr:-J24QLe5-CeY91VeyOicdN4EQ1P9P3zVcXhItRmPUvdRDQ7bav-s2BbJaYZSuzF8XNY81S9gbURG-jUU_Lad3yhQKzuGAZT1B750gmlkgnY0gmlwhCUbX3iHb3BzdGFja4PNNwCJc2VjcDI1NmsxoQJlhOFjYa3U5VvLJZYGTsNqDE-cW8Xqbh8AIIZfnyJdcYN0Y3CCJAeDdWRwgiQH
exec /app/op-node --l2=http://op-reth:8551 \
  --l2.jwt-secret=/config/jwt.txt \
  --sequencer.enabled \
  --sequencer.l1-confs=5 \
  --verifier.l1-confs=4 \
  --rollup.config=/config/rollup.json \
  --rpc.addr=0.0.0.0 \
  --rpc.port=8547 \
  --rpc.enable-admin \
  --l1=$L1_RPC_URL \
  --l1.rpckind=$L1_RPC_KIND \
  --l1.beacon.ignore=true \
  --p2p.listen.ip=0.0.0.0 \
  --p2p.listen.tcp=9223 \
  --p2p.listen.udp=9223 \
  --p2p.sequencer.key=$GS_SEQUENCER_PRIVATE_KEY \
  --p2p.priv.path=/config/op-node-key \
  --altda.enabled="true" \
  --altda.da-service="false" \
  --altda.da-server=http://da-server:3100
#  --altda.da-server=https://r2-da.otternode.com

#  --syncmode=execution-layer \

 # --l1.beacon-archiver=$L1_BEACON_URL \

#  --altda.da-server="http://37.27.129.89:3100" \
#  --altda.da-service="true" \
