#!/bin/sh
set -eu
exec /app/op-proposer \
  --poll-interval=10s \
  --num-confirmations=1 \
  --rpc.port=8560 \
  --rollup-rpc=http://op-node:8547 \
  --l2oo-address=$L2_OO \
  --private-key=$GS_PROPOSER_PRIVATE_KEY \
  --l1-eth-rpc=$L1_RPC_URL \
  --log.level=debug \
  --txmgr.min-basefee="0.000002113" \
  --txmgr.min-tip-cap="0.000002013" \
  --allow-non-finalized=true 

